### ISSUE TITLE
Extract tunable parameters from source code

### ISSUE THREAD

**Issue by ctrltz** [ilyavoronin/preprint_server#15]
We need to be able to launch ArxivCollector from command line at some point, and we don't want to modify source code to tune parameters such as:
 * ArxivCollector.limit - consider using 0 for "no limit" case
 * ArxivCollector.sleepTime
 * CrossRefApi.maxRecordsNumber
 * `val reqLimiter = RequestLimiter(49, 2100)` - line CrossRefApi.kt:17, hardcoded values look like tunable
 * so on...

**Comment by ctrltz** [comment]
Please also add options to configure whether PDFs should be saved, references should be validated.

**Comment by ilyavoronin** [comment]
ArxivCollector doesn't have option to save pdf now. If this option is necessary it can be added later
