### ISSUE TITLE
Data is incorrectly stored in neo4j

### ISSUE THREAD

**Issue by ctrltz** [ilyavoronin/preprint_server#17]
- [x] Year should be stored as int
 - [x] arxivId has redundant 'arXiv:' prefix, I think that it can be removed

See example:

```
{
  "title": "Symmetry-Surfing the Moduli Space of Kummer K3s",
  "pubYear": "2015",
  "arxivId": "arXiv:1303.2931",
  "doi": "10.1090/pspum/090/01522"
}
```

**Comment by ilyavoronin** [comment]
If you are using ArxivValidator 'arxiv' prefix will always be removed. And there is no point in not using it because it just parses arxiv id from a string
